name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login 
      env:
        DOCKER_USER: Sisecrets.DOCKERHUB_USER}}
        DOCKER_PASS: $/{secrets.DOCKERHUB_PASS} 
      run:
        docker login -u SDOCKER_USER -p SDOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile -tag pablobaezs/pokeneas:latest
    - name: Docker Push
      run: docker push pablobaezs/pokeneas
